# Generated by Django 4.2.7 on 2023-11-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='view_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
