# Generated by Django 4.2.7 on 2023-11-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_lesson_view_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='view_time',
            new_name='duration',
        ),
    ]
