# Generated by Django 4.2.7 on 2023-11-28 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_rename_view_time_lesson_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewlesson',
            name='users',
        ),
        migrations.AddField(
            model_name='viewlesson',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
