# Generated by Django 4.2.7 on 2023-11-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_viewlesson_users_viewlesson_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
        migrations.AddField(
            model_name='viewlesson',
            name='status',
            field=models.CharField(choices=[('seen', 'Seen'), ('not seen', 'Not Seen')], default='not seen', max_length=10),
        ),
    ]
