# Generated by Django 4.2.7 on 2023-11-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_viewlesson_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='link',
        ),
        migrations.AlterField(
            model_name='viewlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_lesson', to='product.lesson'),
        ),
    ]
