# Generated by Django 4.2.7 on 2023-11-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_lesson_link_alter_viewlesson_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_permission',
        ),
    ]
