# Generated by Django 4.2.7 on 2023-11-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_lesson_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewlesson',
            old_name='video_record',
            new_name='seen_duration',
        ),
    ]
