# Generated by Django 4.2.7 on 2023-11-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_video_record_viewlesson_seen_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewlesson',
            old_name='users',
            new_name='user',
        ),
    ]
