# Generated by Django 4.2.7 on 2023-11-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_users_viewlesson_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(related_name='lessons', to='product.course'),
        ),
    ]
