# Generated by Django 4.2.7 on 2023-11-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_lesson_course_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='last_seen_time',
        ),
    ]
