# Generated by Django 4.2.7 on 2023-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_lesson_last_seen_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seen_lesson_count',
            field=models.IntegerField(default=0),
        ),
    ]
