# Generated by Django 4.2.7 on 2023-11-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_course_entries_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='seen_lesson_count',
        ),
    ]
